//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoAula4EmanuelGallego_SaraPineda.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EpmEntities : DbContext
    {
        public EpmEntities()
            : base("name=EpmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbAgua> tbAguas { get; set; }
        public virtual DbSet<tbCliente> tbClientes { get; set; }
        public virtual DbSet<tbEnergia> tbEnergias { get; set; }
        public virtual DbSet<tbFactura> tbFacturas { get; set; }
        public virtual DbSet<tbPrecio> tbPrecios { get; set; }
    }
}
